############################################################
#### Configuration
############################################################

# database stuff
# database stuff
sql_server: localhost
sql_user: bbpress
sql_database: bbpress
sql_password: replaceme

# User with admin privileges to create users and category
discourse_admin: forumadmin

# If true then nothing will be written to the Discourse database
test_mode: true
