############################################################
#### Configuration
############################################################

# database stuff
# database stuff
sql_server: bbpress_db
sql_user: bbpress
sql_database: bbpress
sql_password: bbpress

# User with admin privileges to create users and category
discourse_admin: system

# If true then nothing will be written to the Discourse database
test_mode: true
